### ISSUE TITLE
upload_disk.py fails with : "socket.error: [Errno 32] Broken pipe"

### ISSUE THREAD

**Issue by gpavinteractiv** [oVirt/ovirt-engine-sdk#13]
centos 7.5 and ovirt 4.2.7
I try to upload a vm with the upload_disk.py example

I see that the disk gets created in the data domain with "Transferring via Browser", but then if fails to continue and status change to ""Paused by System

On cli I get :
 ````
[root@ps-inf-int-kvm-fr-307 vm]# ./upload_disk.py vs-inf-prd-adm-fr-501.qcow2
Checking image...
Disk format: qcow2
Disk content type: data
Connecting...
Creating disk...
Creating transfer session...
Uploading image...
Traceback (most recent call last):
  File "./upload_disk.py", line 256, in <module>
    proxy_connection.send(chunk)
  File "/usr/lib64/python2.7/httplib.py", line 857, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/ssl.py", line 744, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python2.7/ssl.py", line 710, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe

````

**Comment by machacekondra** [comment]
Can you please open a bug here: https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine-sdk-python

And attach from engine `/var/log/ovirt-imageio-proxy/image-proxy.log` and from host `/var/log/ovirt-imageio/daemon.log` ?
