### ISSUE TITLE
cannot run program "flake8"

### ISSUE THREAD

**Issue by askifyouneed** [oVirt/ovirt-engine-sdk#2]
Sorry but I do not use maven. I tried to run command:
`mvn package`
and I get en error:
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (format-check) on project python-sdk: Command execution failed. Cannot run program "flake8" (in directory "/home/user/ovirt-engine-sdk/sdk"): error=2, No such file or directory -> [He`lp 1]

**Comment by machacekondra** [comment]
What system do you use? You miss the `flake8`, so please install the relevant package for your system.

**Comment by askifyouneed** [comment]
I have got fedora 25.
Earlier I have installed:
`dnf install gcc libxml2-devel python-devel`

**Comment by askifyouneed** [comment]
I have just installed: dnf install python2-flake8, and run mvn package again,
the next problem is:
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (test) on project python-sdk: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]`

**Comment by jhernand** [comment]
Here you have a complete list of all the packages that you need to install in Fedora 25 in order for the build to succeed:

https://github.com/oVirt/ovirt-engine-sdk/blob/master/automation/build.packages.fc25

**Comment by askifyouneed** [comment]
After installed all packages from above, and run: "mvn package"
```
/usr/lib/python2.7/site-packages/nose/config.py:435: DeprecationWarning: Use of multiple -w arguments is deprecated and support may be removed in a future release. You can get the same behavior by passing directories without the -w argument on the command line, or by using the --tests argument in a configuration file.
  DeprecationWarning)
EE..E......................FF..EE........................................................EE......................................
======================================================================
ERROR: Test that reading of `vms` attribute of affinity group reads the `href`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/ovirt-engine-sdk/sdk/tests/test_affinity_group_reader.py", line 52, in test_affinity_group_reader_with_assigned_vms
    assert_true(len(result.vms) > 0)
AttributeError: 'AffinityGroup' object has no attribute 'vms'

```

**Comment by jhernand** [comment]
Make sure you run the `mvn package` command from the top level directory of the project, not from the `sdk` directory.

**Comment by askifyouneed** [comment]
$pwd
`/home/user/ovirt-engine-sdk`
Mabye should I delete all and git clone project again?
And run: mvn package,
I do not understand why there could not be a simple way by: python setup.py install.

**Comment by jhernand** [comment]
Can you submit a patch for the README.adoc file to add the documentation that you consider necessary? Remember to do it using `gerrit.ovirt.org`, as Github is just a mirror.

Note that you don't have to do all this process if all what you want is use the SDK. You can just do `pip install ovirt-engine-sdk-python`. The `mvn ...` command is only needed when you want, for whatever the reason, to re-generate the code of the SDK (most of it is automatically generated from the specification of the API).

**Comment by askifyouneed** [comment]
Ok. I am not familiar with programming because I am an administrator. I have just listed vm machines and it works, but another notice is about certification, because RHEVM got both the main one <rhevm_hostname>24245.crt and the second subcertificate <rhevm_hostname>.crt., and the proper is the main one.
Ok, I will try to do this with pip command, because I plan to write some python script to run on the RHEV host, and import the RAW, because now there is not possible from the RHEVM portal.

**Comment by mykaul** [comment]
@askifyouneed - why not use Ansible? Wouldn't it be easier for you?

**Comment by askifyouneed** [comment]
Ansible? For what? I have to import my virtual machines based on qcow2 storage from one location to the new RHV cluster based on iSCSI, and there is no solution how to do this. Of courste in RHEVM is and option to import via qemu+ssh:// protocol, but it's completly useless and slow. So I will plan to shutdown machine, copy to the new RHEV node local storage, and import it by python script.:)

**Comment by mykaul** [comment]
On Mon, Feb 27, 2017, 10:59 PM askifyouneed <notifications@github.com>
wrote:

> Ansible? For what? I have to import my virtual machines based on qcow2
> storage from one location to the new RHV cluster based on iSCSI, and there
> is no solution how to do this. Of courste in RHEVM is and option to import
> via qemu+ssh:// protocol, but it's completly useless and slow. So I will
> plan to shutdown machine, copy to the new RHEV node local storage, and
> import it by python script.:)
>

I'd ask on the users mailing list for alternative approaches.
Y.

**Comment by askifyouneed** [comment]
Yes please, and thank you for your help.

**Comment by mykaul** [comment]
@askifyouneed - please join @ http://www.ovirt.org/community/about/mailing-lists/#users - there's a very friendly and helpful community which will gladly share their experience with you.
