### ISSUE TITLE
python3 not found python3-ovirt-engine-sdk4 pkg

### ISSUE THREAD

**Issue by Michael754267513** [oVirt/ovirt-engine-sdk#29]
i use python3 and install ovirt-release41.rpm. yum install python3-ovirt-engine-sdk4, package  not found ,if i use python3 what should do?

**Comment by sandrobonazzola** [comment]
oVirt 4.1 had no support for python 3. Also oVirt 4.1 is not supported anymore. Please upgrade to oVirt 4.3.
