### ISSUE TITLE
To perform full + incremental backup using APIs

### ISSUE THREAD

**Issue by nbayapu7** [oVirt/ovirt-engine-sdk#30]
Ovirt Vesrion : 4.3.9
Libvirt version: 4.5.0-23
Kernel : 3.10.0-1062.18.1.el7.x86_64

`curl -v --insecure -X POST --header "Accept:application/xml" --header "Content-Type:application/xml" --user ' ' \
                --data @$post_call_file $q_url`

`Post data: 
<backup>
        <disks>
                <disk id="225eb867-15c9-4cab-82be-e52516f******" />
        </disks>
</backup>`
`
I'm try full backup using above API call and backup is failing with following error.

`<fault>
    <detail>[Cannot backup VM. Backup is not supported by the host (node5).]</detail>
    <reason>Operation Failed</reason>
</fault>
`
Based on the msg in below given url, seems fullback and incremental backup functionality is not implemented in the version I have. Just API has been written for this. And backup capability work is being done.

https://www.mail-archive.com/devel@ovirt.org/msg15875.html

Has anyone tested atleast full backup with ovirt v4.3.9 using direct API or python SDK?

**Comment by oliel** [comment]
Hi @nbayapu7, some time has passed since you've submitted this issue, is it still relevant? We use [bugzilla](https://bugzilla.redhat.com/) to report issues for this project (this is why took long to notice it). If it's still relevant, could you please report it through bugzilla?

**Comment by sandrobonazzola** [comment]
oVirt 4.3 reached EOL long time ago, if this can be reproduced on oVirt 4.4 please open a ticket on https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine-sdk-python
