### ISSUE TITLE
4.4 ISO_DOMAIN deprecated, not sure how to search only ISOs on data domain.

### ISSUE THREAD

**Issue by csreynolds** [oVirt/ovirt-engine-sdk#31]
In prep for 4.3 -> 4.4 migration, I'm trying to update scripts. 

This is currently how I am finding an iso to attach to a VM for OS loading on nightly builds.

```
storage_domains_service = connection.system_service().storage_domains_service()
storage_domains = storage_domains_service.list()

for storage_domain in storage_domains:
    if(storage_domain.type == types.StorageDomainType.ISO):
        lister = storage_domains_service.storage_domain_service(storage_domain.id)
        file_service = lister.files_service()
        files = file_service.list()
        for file in files:
            print("%s" % (file.name))
```
It works fine with the if statement constraining listing files on StoragDomainType.ISO. If I take the if statement out. the listing fails with the error:
```
Traceback (most recent call last):
  File "listISOs.py", line 26, in <module>
    files = file_service.list()
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/services.py", line 10826, in list
    return self._internal_get(headers, query, wait)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 211, in _internal_get
    return future.wait() if wait else future
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 208, in callback
    self._check_fault(response)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 130, in _check_fault
    body = self._internal_read_body(response)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 312, in _internal_read_body
    self._raise_error(response)
  File "/usr/lib64/python3.6/site-packages/ovirtsdk4/service.py", line 118, in _raise_error
    raise error
ovirtsdk4.NotFoundError: HTTP response code is 404.
```

I can't see anywhere in examples or docs how the storage domains differ. Help? :)

It's not crazy urgent because the ISO_DOMAIN can still exist in 4.4, but I'd like to be up to date to avoid compatibility issues in the future.

installed related bits:
```
rpm -qa | grep ovirt
ovirt-imageio-common-2.2.0-0.202010221524.gitaf57880.el8.x86_64
python3-ovirt-engine-sdk4-4.4.6-1.20201021git465ddd1.el8.x86_64
ovirt-release-master-4.4.3-0.0.master.20201025011129.git17dce40.el8.noarch
ovirt-imageio-client-2.2.0-0.202010221524.gitaf57880.el8.x86_64
```

Semi-related:
The example code [here](https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/python_sdk_guide/index#Listing_Files_in_an_ISO_Storage_Domain) gives the following error:
```
ISO_DOMAIN:

Traceback (most recent call last):
  File "listISOs.py", line 18, in <module>
    files = storage_domain.files_service().list()
AttributeError: 'StorageDomain' object has no attribute 'files_service'
```

**Comment by oliel** [comment]
Hi @csreynolds , some time has passed since you've submitted this issue, is it still relevant? We use [bugzilla](https://bugzilla.redhat.com/) to report issues for this project (this is why took long to notice it). If it's still relevant, could you please report it through bugzilla?

**Comment by csreynolds** [comment]
Yes, it still behaves the same.

**Comment by sandrobonazzola** [comment]
@csreynolds can you please open a ticket on https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine-sdk-python ? it would help planning the work on this issue for the next releases.

**Comment by csreynolds** [comment]
> @csreynolds can you please open a ticket on https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine-sdk-python ? it would help planning the work on this issue for the next releases.

Sorry, I didn't add comment last week, bugzilla issue here: https://bugzilla.redhat.com/show_bug.cgi?id=1953765
