### ISSUE TITLE
Clarification on RPMs

### ISSUE THREAD

**Issue by bsolomon1124** [oVirt/ovirt-engine-sdk#33]
We install the ovirt-engine-sdk via RPM after adding resource.ovirt.org as a repo, for example:

```bash
yum-config-manager --add-repo='https://resources.ovirt.org/repos/ovirt/tested/4.3/rpm/el7/'
```

I've noticed two different subdirectories on resource.ovirt.org and am unclear of the difference:

- https://resources.ovirt.org/repos/ovirt/tested/4.3/rpm/el7/x86_64/
  - This contains python-ovirt-engine-sdk4-4.3.4-2.20200423git62b664f.el7.x86_64.rpm
- https://resources.ovirt.org/pub/ovirt-4.3/rpm/el7/x86_64/
  - This contains python-ovirt-engine-sdk4-4.3.4-2.el7.x86_64.rpm

What is the difference here? Which of these is advised for production?

**Comment by mwperina** [comment]
Hi,

tested repositories are only for development and CI. For production you should always install relevent ovirt-releaseXY RPM package, which contains productionn repositories. In your case for 4.3, you should use:

```
yum install https://plain.resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm
```

Also please be aware that officially we are using Bugzilla for oVirt Python SDK project, so we are not looking regularly on GitHub Issues:

https://www.ovirt.org/community/#report-bugs-and-new-feature-requests-rfes

So please use Bugzilla in future to get faster response.

Thanks a lot,
Martin
