### ISSUE TITLE
overwrites /dev/null with pycurl cookie jar

### ISSUE THREAD

**Issue by rwmjones** [oVirt/ovirt-engine-sdk#34]
With recent PyCurl (at least in Fedora 34) `/dev/null` is overwritten if you use the SDK as root.

The reason is because of the following code:
https://github.com/oVirt/ovirt-engine-sdk/blob/1bb6c5e405ae3d7cd787cce9ea83775393d10e8e/sdk/lib/ovirtsdk4/__init__.py#L392-L394

You can demonstrate this pretty easily with a tiny test program (**NB** be aware before running this that it will destroy your `/dev/null` and make your system unusable!)

```
$ cat curl.py
#!/usr/bin/python3

import pycurl

curl = pycurl.Curl()
curl.setopt(pycurl.COOKIEFILE, '/dev/null')
curl.setopt(pycurl.COOKIEJAR, '/dev/null')

$ sudo ./curl.py 

$ ll /dev/null 
-rw-r--r--. 1 root root 136 Mar 16 13:40 /dev/null
```

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1939387#c6

**Comment by nyoxi** [comment]
I am wondering why this is needed in the first place, because it should be disabled by default: https://curl.se/libcurl/c/CURLOPT_COOKIEJAR.html
But I assume user can override it with environment variable maybe?

It looks like there is a bug in pycurl wrapper also, because you cannot "undefine" the value. Using `None` or `0` does not seem to work and produces errors:

```
...
Traceback (most recent call last):
  File "/tmp/tmp.6pLX6iXQx8/curl.py", line 7, in <module>
    curl.setopt(pycurl.COOKIEFILE, None)
TypeError: unsetopt() is not supported for this option
...
Traceback (most recent call last):
  File "/tmp/tmp.6pLX6iXQx8/curl.py", line 7, in <module>
    curl.setopt(pycurl.COOKIEFILE, 0)
TypeError: integers are not supported for this option
```

**Comment by rwmjones** [comment]
I checked with the C API and it does allow you to set the cookie jar to `NULL`.

The current libcurl implementation only has `"-"` as a special value (meaning to write the cookies out to stdout on exit).  Every other non-NULL value is treated as a filename and will cause the named file to be overwritten when the curl handled is cleaned up.

I was also interested in this phrase in the manual page: *Using this option also enables cookies for this session, so if you for example follow a location it will make matching cookies get sent accordingly.*  This is indeed true, and is the only way to activate cookies per handle.  Perhaps this is what the author was intending by calling these methods?

Anyway I would suggest setting this to some temporary filename or even something under `/dev/shm` if the aim is to enable cookies while not writing to any particular file.

**Comment by sandrobonazzola** [comment]
@rwmjones hi, can you please open a bz on https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine-sdk-python ?
Thanks.

**Comment by rwmjones** [comment]
BZ says I must select a component for the bug, but no components are shown in the drop-down list, so I cannot file this bug.  If you can file it then I will link it to our RHEL bug.

**Comment by sandrobonazzola** [comment]
Thanks @rwmjones closing the ticket here, we'll track progress on the bz at https://bugzilla.redhat.com/show_bug.cgi?id=1956750
