### ISSUE TITLE
vm_backup.py fails

### ISSUE THREAD

**Issue by archy9** [oVirt/ovirt-engine-sdk#4]
Then trying to run script configured for ovirt instalation to test it fails 
Traceback (most recent call last):
  File "backup.py", line 87, in <module>
    )[0]
IndexError: list index out of range
in logfile is nothing about error only output from console

**Comment by mykaul** [comment]
I assume it cannot find the VM you are looking for.
Note that this is just an example script, it does not have all the protections to ensure correct input.
Y.

**Comment by archy9** [comment]
thank for providing info, i found my mistake - so bug can be deleted
