### ISSUE TITLE
How to list the disks in a particular storage domain.

### ISSUE THREAD

**Issue by sathvikm** [oVirt/ovirt-engine-sdk#7]
Hi All, 
Can someone help in listing all the disks in a  particular storage domain. Using below lines I am able to fetch all the disks from all the storage domains.          

```
disks_service = system_service.disks_service()
disks = disks_service.list()
```
Thanks, 
Sathvik M

**Comment by rollandf** [comment]
Hi,
It is better to send this kind of questions to users@ovirt.org mailing list.

You can try this way:
`sds_service = connection.system_service().storage_domains_service()
vms = sds_service.list()
sd_service = sds_service.storage_domain_service("621fa52b-3384-404e-8c6c-f6077699cc06")
disks = sd_service.disks_service().list()`

**Comment by sathvikm** [comment]
TQ @rollandf for the quick reply. Now am able list the disks in a particular storage domain.
