### ISSUE TITLE
ovirtSDK4.x edit memory and CPU ？

### ISSUE THREAD

**Issue by Michael754267513** [oVirt/ovirt-engine-sdk#9]
ovirt3.x： 
      update memory：
                 vm.memory = 32 * 2 **30
                 vm.update()
ovirt4.x：
     update memory：
                vm.memory = 32 * 2 **30
                vm.update() # not found

**Comment by mykaul** [comment]
Please open issues in Bugzilla - this is a read-only mirror of our Gerrit repository.
Have you looked at the APIv4 examples?

**Comment by Michael754267513** [comment]
@mykaul  I can`t find about editCPU and edit memory in sdk4.x, and search keywords  cpu or memory the results "sdk/examples/add_instance_type.py", this example is create Resource package，
for example：
         the VM is running  to edit memory and cpu。

**Comment by machacekondra** [comment]
If you look for here, it's example how to update datacenter:

https://github.com/oVirt/ovirt-engine-sdk/blob/69610949da7f4ae02c7e87493fc3e48dc8b026d2/sdk/examples/update_data_center.py#L40-L54

The same way you go with VMs, but using vms_service.

```python
vms_service = connection.system_service().vms_service()
vms = vms_service.list(search='name=myvm')[0]
vm_service = vms_service.vm_service(vm.id)
vm = vm_service.update(
    types.Vm(
        memory=32 * 2 **30,
    ),
)
```

**Comment by Michael754267513** [comment]
TKS
